config/routes.rb
Rails.application.routes.draw do
  resources :top_bar, only: [:index]
  resources :home, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def only_turbo
    return if turbo_frame_request?
    render plain: "This controller only responds to Turbo Frame requests",
           status: :not_acceptable
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/top_bar_controller.rb
class TopBarController < TurboOnlyController
  def index
  end

  layout "top_bar"
end

app/controllers/turbo_only_controller.rb
class TurboOnlyController < ApplicationController
  class NoLayoutProvidedError < StandardError
  end

  prepend_before_action :only_turbo

  layout -> {
           raise NoLayoutProvidedError,
                 "Class that inherits from #{self.class} must provide a layout"
         }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to "Link to this page", home_index_path %>

app/views/layouts/_main.html.erb
<%= turbo_frame_tag :main do %>
  <%= yield %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestTurbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= turbo_frame_tag :top_bar, src: top_bar_index_path %>

    <%= render 'layouts/main' do %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/layouts/top_bar.html.erb
<html>
  <head>
    <%= yield :head %>
  </head>
  <body>
    <%= turbo_frame_tag :top_bar do %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/layouts/turbo_rails/frame.html.erb
<html>
  <head>
    <%= yield :head %>
  </head>
  <body>
    <%= render 'layouts/main' do %>
      <%= yield %>
    <% end %>
  </body>
</html>

app/views/top_bar/index.html.erb
<h1>TopBar#index</h1>
<p>Find me in app/views/top_bar/index.html.erb</p>
<%= link_to "Link to this page", top_bar_index_path %>